version: '2'
services:
    db:
        image: postgres:13
        restart: always
        env_file:
            - .env
        ports:
            - 5432:5432
        expose:
            - 5432
    raffle:
        build: .
        stdin_open: true
        tty: true
        volumes:
            - ".:/opt/RAFFLE"
        ports:
            - 3000:3000
        depends_on:
            - db
            - redis
        env_file:
            - .env
    sidekiq:
        build: .
        command: bundle exec sidekiq
        depends_on:
            - db
            - redis
        env_file:
            - .env
    redis:
        image: redis
