default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['RAILS_API_BOILERPLATE_DB_PASSWORD'] %>
  host: <%= ENV['RAILS_API_BOILERPLATE_DB_HOST'] %>
  database: <%= ENV['RAILS_API_BOILERPLATE_DB_NAME'] %>

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
