default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_DB_HOST'] %>
  database: <%= ENV['POSTGRES_DB'] %>

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
